name: Generate GitHub Contributions SVG

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Contributions Image
    steps:
      - uses: actions/checkout@v2
      - uses: DenverCoder1/github-contributions-readme@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: azureun
          config-file: "./contrib-readme-config.json"
